do
msgbox"You're computer hacked bro"
msgbox"you can't do anything"
msgbox"you're motherfucker shutup"
msgbox"fuck you"
msgbox"fuck you"
msgbox"fuck you"
msgbox"fuck you"
msgbox"fuck you"
msgbox"fuck you"
msgbox"fuck you"
msgbox"fuck you"
msgbox"fuck you"
msgbox"fuck you"
msgbox"fuck you"
msgbox"fuck you"
msgbox"fuck you"
msgbox"fuck you"
msgbox"fuck you"
msgbox"fuck you"
msgbox"fuck you"
msgbox"fuck you"
msgbox"fuck you"
msgbox"fuck you"
msgbox"fuck you"
msgbox"fuck you"
msgbox"fuck you"
msgbox"fuck you"
msgbox"fuck you"
msgbox"fuck you"
msgbox"fuck you"
msgbox"fuck you"
msgbox"you scaredy cat"
loop
